# Generated by Google Gemini

import io
import os
from markitdown import MarkItDown, StreamInfo
from Products.zms.standard import pybool
from ZPublisher.interfaces import IPubSuccess

MD_CONVERTER = MarkItDown()


def transform_html_to_markdown(event):
    """
    Subscribes to IPubSuccess (guaranteed execution at request end).
    """
    request = event.request
    response = request.response

    if not pybool(os.getenv('ZMS_ENABLE_MARKDOWN_RENDERING')):
        return

    # path = request.get('PATH_INFO', '').lower()
    # if 'index' in path and path.endswith('.md'):
    #   -> needs adjustments to Products.zms._pathhandler and Products.zms.zmsobject.py
    #   -> see https://github.com/zms-publishing/zms.unibe/blob/main/index.md.patch

    query = request.get('QUERY_STRING', '').lower()

    if 'transform=markdown' in query:
        # 1. Grab the finalized content body from the response
        body = response.body

        if not body:
            return

        if isinstance(body, str):
            html_bytes = body.encode('utf-8', errors='ignore')
        else:
            html_bytes = body

        try:
            # 2. Run MarkItDown execution
            html_stream = io.BytesIO(html_bytes)
            stream_info = StreamInfo(
                extension=".html",
                mimetype="text/html",
                charset="utf-8"
            )
            result = MD_CONVERTER.convert_stream(html_stream, stream_info=stream_info)

            markdown_text = result.text_content or ""
            markdown_bytes = markdown_text.encode('utf-8')

            # 3. Force overwrite the body directly on the response instance
            response.body = markdown_bytes

            # 4. Enforce plain markdown headers
            response.setHeader('content-type', 'text/markdown; charset=utf-8')
            response.setHeader('content-length', str(len(markdown_bytes)))

        except Exception:
            pass  # Keep original rendering on error
