# Generated by Google Gemini

import io
import os
from markitdown import MarkItDown  #, StreamInfo
from Products.zms.standard import pybool
from ZPublisher.interfaces import IPubSuccess

global MD_CONVERTER
global IS_MD_ENABLED

def initialize():

    global IS_MD_ENABLED
    IS_MD_ENABLED = pybool(os.getenv('ZMS_ENABLE_MARKDOWN_RENDERING'))

    if IS_MD_ENABLED:    
        print('Handler: zms.unibe.utils.subscribers.transform_html_to_markdown'
              ' registered for ZPublisher.interfaces.IPubSuccess')
        
        global MD_CONVERTER
        MD_CONVERTER = MarkItDown()

    print('Handler: zms.unibe.utils.subscribers.add_csp_headers'
          ' registered for ZPublisher.interfaces.IPubSuccess')
    
initialize()


def add_csp_headers(event):
    """
    Subscribes to IPubSuccess (guaranteed execution at request end).
    """
    request = event.request
    response = request.response
    parents = request.get('PARENTS', [])
    path = request.get('PATH_INFO', '').lower()
    
    # Add CSP headers only for index_*.html pages
    # e.g. index_ger.html, index_eng.html, index_fra.html
    if 'index_' not in path or not path.endswith('.html'):
        return

    # This default CSP header will be set at portal master as ZMS system property 'csp_header'
    # and can be overridden in each client's ZMS system properties.
    # csp_header = "frame-ancestors 'self' https://unibe.ch https://*.unibe.ch; report-uri /csp-report; report-to csp;"

    try:
        csp_header = parents[0].content.getConfProperty('csp_header', None)
    except Exception:
        csp_header = None
        pass

    if csp_header:
        response.setHeader('Reporting-Endpoints', 'csp="/csp-report"')
        response.setHeader('Content-Security-Policy', csp_header)



def transform_html_to_markdown(event):
    """
    Subscribes to IPubSuccess (guaranteed execution at request end).
    """
    if not IS_MD_ENABLED:
        return

    request = event.request
    response = request.response

    # path = request.get('PATH_INFO', '').lower()
    # if 'index' in path and path.endswith('.md'):
    #   -> needs adjustments to Products.zms._pathhandler and Products.zms.zmsobject.py
    #   -> see https://github.com/zms-publishing/zms.unibe/blob/main/src/zms/unibe/patches/index.md.patch

    query = request.get('QUERY_STRING', '').lower()

    if any(part == 'transform=markdown' for part in query.split('&')):
        # 1. Grab the finalized content body from the response
        if 'text/html' not in (response.getHeader('content-type') or '').lower():
            return
        body = response.body

        if not body:
            return

        if isinstance(body, str):
            html_bytes = body.encode('utf-8', errors='ignore')
        else:
            html_bytes = body

        try:
            # 2. Run MarkItDown execution
            html_stream = io.BytesIO(html_bytes)
            # stream_info = StreamInfo(
            #     extension=".html",
            #     mimetype="text/html",
            #     charset="utf-8"
            # )
            # -> requires https://github.com/microsoft/markitdown/releases/tag/v0.1.0 or later
            # see https://github.com/zms-publishing/zms.unibe/commit/d1be8d6b2109c32a9f121dfbcffec0df23812f32
            result = MD_CONVERTER.convert_stream(html_stream, file_extension=".html")  # stream_info=stream_info)

            markdown_text = result.text_content or ""
            markdown_bytes = markdown_text.encode('utf-8')

            # 3. Force overwrite the body directly on the response instance
            response.body = markdown_bytes

            # 4. Enforce plain markdown headers
            response.setHeader('content-type', 'text/markdown; charset=utf-8')
            response.setHeader('content-length', str(len(markdown_bytes)))

        except Exception:
            pass  # Keep original rendering on error
