import uvicorn
import os
from fastapi import FastAPI
from fastapi.responses import RedirectResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware

from cmsapi.metadata import cmsapi_tags
from cmsapi.routers import newsevents, zmsobjects, zmscontent, servicelinks, uniaktuell, mediareleases

app = FastAPI(title="CMSAPI v3",
              version="3.1.1",
              description="Python-based REST API for retrieving, analyzing and consolidating content "
                          "published in UniBE-CMS and other information systems.",
              docs_url="/v3/swagger",
              redoc_url="/v3/redoc",
              openapi_url="/v3/openapi.json",
              openapi_tags=cmsapi_tags,
              swagger_ui_parameters={"defaultModelsExpandDepth": -1})

origins = [
    "http://localhost:63342",  # TODO: adjust CORS hosts/ports
    "http://127.0.0.1:63342",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# generated by 'mkdocs build' in /site
app.mount("/v3/docs", StaticFiles(directory=f"{os.path.abspath(os.path.dirname(__file__))}/../site", html=True))

app.include_router(newsevents.router)
app.include_router(uniaktuell.router)
app.include_router(mediareleases.router)
app.include_router(servicelinks.router)
app.include_router(zmsobjects.router)
app.include_router(zmscontent.router)


@app.get("/v3", include_in_schema=False)
def redirect_docs():
    return RedirectResponse("/v3/docs")


@app.get("/v3/healthcheck", include_in_schema=False)
def check_health():
    return PlainTextResponse("OK", 200)


if __name__ == '__main__':
    uvicorn.run(app, host="127.0.0.1", port=5003)
