import uvicorn
import os
from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from fastapi.staticfiles import StaticFiles

from .metadata import cmsapi_tags
from .routers import newsevents, zmsobjects, mobileapp, uniaktuell, mediareleases

app = FastAPI(title="CMSAPI v3",
              version="3.0.0beta",
              description="Python-based REST API for retrieving, analyzing and consolidating content "
                          "published in UniBE-CMS and other information systems.",
              docs_url="/swagger",
              openapi_url="/v3/openapi.json",
              openapi_tags=cmsapi_tags,
              swagger_ui_parameters={"defaultModelsExpandDepth": -1})

# generated by 'mkdocs build' in /site
app.mount("/docs", StaticFiles(directory=f"{os.path.abspath(os.path.dirname(__file__))}/../site", html=True))

app.include_router(newsevents.router)
app.include_router(uniaktuell.router)
app.include_router(mediareleases.router)
app.include_router(mobileapp.router)
app.include_router(zmsobjects.router)


@app.get("/", include_in_schema=False)
def redirect_docs():
    return RedirectResponse("/docs")


if __name__ == '__main__':
    uvicorn.run(app, host="127.0.0.1", port=5003)
