# Prerequisites:
# - https://github.com/zms-publishing/zms.unibe/tree/main/dev#checkout-and-install-on-localhost
# - https://github.com/zms-publishing/zms.unibe/tree/main/dev#checkout-and-link-the-content-models
# - set COMPOSE_INCLUDE=dev in versions.env

services:
  zms:
    develop:
      # [BUG] develop.watch initial_sync: true does not fire at container start
      # https://github.com/docker/compose/issues/13725
      watch:
        - path: ./dev/zope/src
          target: /app/zope/src/zope/src
          action: sync+restart
          initial_sync: true
        - path: ./dev/products-zms/Products/zms
          target: /app/zope/src/products-zms/Products/zms
          action: sync+restart
          initial_sync: true
    volumes:
      - ./dev/unibe-cms-models/frontend/zms/models:/app/frontend/zms/models:rw

  fastapi:
    develop:
      # [BUG] develop.watch initial_sync: true does not fire at container start
      # https://github.com/docker/compose/issues/13725
      watch:
        - path: ./dev/zope/src
          target: /app/zope/src/zope/src
          action: sync+restart
          initial_sync: true
        - path: ./dev/products-zms/Products/zms
          target: /app/zope/src/products-zms/Products/zms
          action: sync+restart
          initial_sync: true
