ARG BASE_IMAGE
# TODO: make the dependent base image generally available (GA)
FROM ghcr.io/idasm-unibe-ch/unibe-cms:$BASE_IMAGE

ARG ZOPE_VERSION
ARG ZMS_CORE_BRANCH_OR_COMMIT
ARG ZMS_UNIBE_BRANCH_OR_COMMIT
ARG SETUPTOOLS_VERSION

USER $USERNAME

RUN python3 -m venv $VENV_HOME \
 && $VENV_HOME/bin/pip install --upgrade pip wheel setuptools==$SETUPTOOLS_VERSION \
    -e "Zope[wsgi] @ git+https://github.com/zopefoundation/Zope.git@$ZOPE_VERSION" \
    -e "Products.zms @ git+https://github.com/zms-publishing/ZMS.git@$ZMS_CORE_BRANCH_OR_COMMIT" \
    -e "zms.unibe[fastapi] @ git+https://github.com/zms-publishing/zms.unibe.git@$ZMS_UNIBE_BRANCH_OR_COMMIT" \
    -c "https://raw.githubusercontent.com/zopefoundation/Zope/$ZOPE_VERSION/constraints.txt" \
    -c "https://raw.githubusercontent.com/zms-publishing/zms.unibe/$ZMS_UNIBE_BRANCH_OR_COMMIT/constraints.txt"

WORKDIR /app/zope/src/zms-unibe

CMD ["/app/zope/bin/fastapi", "dev", "--host", "0.0.0.0", "--port", "8000"]