# Docker stack to be deployed on localhost for development
# For test-unibe-cmsapi stack to be deployed in Docker Swarm cluster see
# https://id-code.unibe.ch/projects/EPDOCKER/repos/docker-config-test/browse/stacks/test-unibe-cmsapi/docker-compose.yml

version: '3.7'

networks:
  worker:
  cms_network:

services:

  api:
    image: ep-devops.id.unibe.ch:5000/id/unibe-cmsapi-v3:local
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 768M
    ports:
      - 5553:5003
    volumes:
      - /Users/cm19b120/PyCharm/ENV/logs:/app/log
    environment:
      - PYTHONUNBUFFERED=true
      - ZODB_STORAGE=zeo:8000?storage=main
      - SQLDB_STORAGE=postgres:mysecretpassword@sql:5432/unibe_cmsapi
    networks:
      - worker
      - cms_network

  sql:
    image: postgres:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 768M
    ports:
      - 5432:5432
    volumes:
      - /Users/cm19b120/PyCharm/ENV/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - cms_network

volumes:
  extensions:
    driver: local

  mediadb:
    driver: local

  zodb:
    driver: local

  logs:
    driver: local