version: '3.2'

services:

  zms-headless-interface:
    build: .
    ports:
      - 5000:5000
    # TODO checkout from unibe-git via ssh
    # TODO mount does not work - because out of context?!?
    #volumes:
    #  - /Users/cm19b120/Workspace/UniBE/Flask/zms4:/restapi/zms4-headless
    depends_on:
      - zeo-zodb-storage # => rw
      - sql-postgres-storage

  zms-publishing-frontend:
    build: ../../zms4
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - zeo-zodb-storage # => ro

  zms-editing-backend:
    build: ../../zms4
    env_file:
      - .env
    ports:
      - 9080:8080
    depends_on:
      - zeo-zodb-storage # => rw

  zeo-zodb-storage:
    build: ../../zms4
    entrypoint: bin/runzeo -a  zeo-zodb-storage:9100 -f /zms4/var/Data.fs
    env_file:
      - .env
    volumes:
      - zodb:/zms4/var/
    ports:
      - 9100:9100

  sql-postgres-storage:
    image: postgres:9.5
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  zodb:
  postgres:
