FROM ep-devops.id.unibe.ch:5000/id/unibe-cmsbase:python3.10.4-zope5.5.1

ENV ZODB_STORAGE="zeo:8000?storage=main" \
    ACCESS_LOG_DIR="/app/log" \
    ERROR_LOG_DIR="/app/log"

RUN apk update \
 && apk --no-cache add \
    libpq-dev

COPY zms-headless $APPHOME/zms-headless
COPY requirements-fastapi.txt $APPHOME/requirements-fastapi.txt
COPY constraints-fastapi.txt $APPHOME/constraints-fastapi.txt

RUN $APPHOME/bin/pip install \
    -r $APPHOME/requirements-fastapi.txt \
    -c $APPHOME/constraints-fastapi.txt \
    -c https://zopefoundation.github.io/Zope/releases/5.5.1/constraints.txt

# TODO: reactivate for model inspection
# COPY frontend/ZMSModels $APPHOME/frontend/ZMSModels
COPY cmsapi $APPHOME/cmsapi
# generated by 'mkdocs build' in /site and to be served as StaticFiles at /docs (see cmsapi.main)
COPY site $APPHOME/site
COPY cron/afterwork /etc/periodic/afterwork
COPY cron/officehours /etc/periodic/officehours
COPY init_scripts $ENTRYPOINT_SCRIPTS