#!/bin/bash

now=$(date)
echo "$now cmsadm update --metaobj InfoBox --metaobj ContentTabs --metaobj TwoCols --metaobj TeaserContainer2022 --metaobj ZMSGraphic"
echo "==========================================================================" >> $VENV_HOME/log/api-cron.log
echo $now >> $VENV_HOME/log/api-cron.log
echo "--------------------------------------------------------------------------" >> $VENV_HOME/log/api-cron.log
$VENV_HOME/bin/python -m cmsapi.admin.main update \
  --metaobj InfoBox \
  --metaobj ContentTabs \
  --metaobj TwoCols \
  --metaobj TeaserContainer2022 \
  --metaobj ZMSGraphic \
  --metaobj Person \
  --metaobj ContactBoxSection \
  --metaobj ContactBox \
  --metaobj TeamSection \
  --metaobj Team \
  &>> $VENV_HOME/log/api-cron.log




