# https://relstorage.readthedocs.io/en/latest/zodbconvert.html

<filestorage source>
    path ../unibe-cms/docker/mounts/data/Data.fs
</filestorage>

<relstorage destination>
    <sqlite3>
        data-dir ../unibe-cms/docker/mounts/data/sqlite
    </sqlite3>
</relstorage>
