%import relstorage

<zodb_db main>
    <relstorage>
        # https://relstorage.readthedocs.io/en/latest/postgresql/index.html
        # https://relstorage.readthedocs.io/en/latest/relstorage-options.html#blobs
        # if shared-blob-dir false (the default, and recommended)
        # then blob-dir is treated as a local cache
        # (actual blob data is stored in the relational database)
        shared-blob-dir false
        blob-dir $INSTANCE/var/cache_blobs
        blob-cache-size 20gb
        <postgresql>
            dsn dbname='$(ZODB_RELSTORAGE_DB_NAME)' user='$(ZODB_RELSTORAGE_DB_USER)' password='$(ZODB_RELSTORAGE_DB_PASSWORD)' host='$(ZODB_RELSTORAGE_DB_HOST)'
        </postgresql>
    </relstorage>
    mount-point /
</zodb_db>

# just to experiment with sqlite3 and zodb mount points, not for production use
<zodb_db sqlite>
    <relstorage>
        # https://relstorage.readthedocs.io/en/latest/sqlite3/faq.html
        # https://relstorage.readthedocs.io/en/latest/sqlite3/options.html
        <sqlite3>
            data-dir $INSTANCE/var
            <pragmas>
                synchronous off
                checkpoint_fullfsync off
                defer_foreign_keys on
                fullfsync off
                ignore_check_constraints on
                foreign_keys off
            </pragmas>
        </sqlite3>
    </relstorage>
    mount-point /sqlite
</zodb_db>

<zodb_db temporary>
    <mappingstorage>
    </mappingstorage>
    container-class Products.TemporaryFolder.TemporaryContainer
    mount-point /temp_folder
</zodb_db>
