# https://relstorage.readthedocs.io/en/latest/zodbconvert.html

<filestorage source>
    path ../unibe-cms/docker/mounts/data/Data.fs
</filestorage>

<relstorage destination>
    <postgresql>
        dsn dbname='zodb' user='postgres' password='thisIsMyRoot' host='localhost'
    </postgresql>
</relstorage>
