#!/bin/bash

now=$(date)
echo $now cmsadm update ServiceLinks
echo "==========================================================================" >> $VENV_HOME/log/api-cron.log
echo $now >> $VENV_HOME/log/api-cron.log
echo "--------------------------------------------------------------------------" >> $VENV_HOME/log/api-cron.log
$VENV_HOME/bin/zms2sql-update-servicelinks &>> $VENV_HOME/log/api-cron.log