#!/bin/bash

now=$(date)
echo $now cmsadm update Announcements
echo "==========================================================================" >> $VENV_HOME/log/api-cron.log
echo $now >> $VENV_HOME/log/api-cron.log
echo "--------------------------------------------------------------------------" >> $VENV_HOME/log/api-cron.log
$VENV_HOME/bin/zms2sql update-mediareleases &>> $VENV_HOME/log/api-cron.log
$VENV_HOME/bin/zms2sql update-uniaktuell &>> $VENV_HOME/log/api-cron.log