#!/bin/bash

now=$(date)
echo $now cmsadm update NewsBoxes
echo "==========================================================================" >> /app/log/api-cron.log
echo $now >> /app/log/api-cron.log
echo "--------------------------------------------------------------------------" >> /app/log/api-cron.log
/app/bin/python -m cmsapi.admin.main update NewsBoxes >> /app/log/api-cron.log