#!/bin/bash

now=$(date)
echo $now cmsadm update --metaobj all
echo "==========================================================================" >> /app/log/api-cron.log
echo $now >> /app/log/api-cron.log
echo "--------------------------------------------------------------------------" >> /app/log/api-cron.log
/app/bin/python -m cmsapi.admin.main update --metaobj all >> /app/log/api-cron.log