name: Deploy Docker image
on:
  workflow_call:
    inputs:
      environment:
        description: "The job environment"
        required: true
        type: string
jobs:
  deploy-image:
    runs-on: self-hosted
    environment: ${{ inputs.environment }}
    env:
      PORTAINER_WEBHOOK_URLS: ${{ vars.PORTAINER_WEBHOOK_URLS }}
      IMAGE_TAG: ${{ inputs.environment }}
    steps:
      - name: Call Portainer webhook URL
        if: ${{ env.PORTAINER_WEBHOOK_URLS != '' }}
        run: |
          echo $PORTAINER_WEBHOOK_URLS | jq -c '.[]' | while read i; do
            curl -X POST ${i}?tag=${IMAGE_TAG}
          done
